# Generated by Django 3.2.23 on 2024-04-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_review_reviews_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviews_count',
        ),
    ]
