# Generated by Django 3.2.23 on 2024-01-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231223_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
