# Generated by Django 3.2.23 on 2024-01-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_friendly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='brand',
        ),
    ]
