# Generated by Django 3.2.23 on 2024-01-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_sku_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='form',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
