# Generated by Django 3.2.23 on 2024-04-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(null=True),
        ),
    ]
